apiVersion: backing.google.com/v1alpha1
kind: Binding
metadata:
  name: foo-binding
  namespace: foo
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: foo-app
  backings:
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLDatabase
    name: {DB_NAME_1}
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLUser
    name: {DB_USER_1}
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLInstance
    name: {INSTANCE_NAME_1}
  - apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: {BUCKET_NAME_1}
  # - apiVersion: sql.cnrm.cloud.google.com/v1beta1
  #   kind: SQLDatabase
  #   name: {DB_NAME_2}
  # - apiVersion: sql.cnrm.cloud.google.com/v1beta1
  #   kind: SQLUser
  #   name: {DB_USER_2}
  # - apiVersion: sql.cnrm.cloud.google.com/v1beta1
  #   kind: SQLInstance
  #   name: {INSTANCE_NAME_2}
  # - apiVersion: storage.cnrm.cloud.google.com/v1beta1
  #   kind: StorageBucket
  #   name: {BUCKET_NAME_2}
---
apiVersion: backing.google.com/v1alpha1
kind: Binding
metadata:
  name: foo-binding-ksvc
  namespace: foo
spec:
  subject:
    apiVersion: serving.knative.dev/v1 # Current version of Knative
    kind: Service
    selector:
      matchLabels:
        app: foo-app
  backings:
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLDatabase
    name: {DB_NAME_1}
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLUser
    name: {DB_USER_1}
  - apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLInstance
    name: {INSTANCE_NAME_1}
  - apiVersion: storage.cnrm.cloud.google.com
    kind: StorageBucket
    name: {BUCKET_NAME_1}