apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    label-one: "value-one"
  name: {BUCKET_NAME_1}
  namespace: foo
spec:
  bucketPolicyOnly: true
  versioning:
    enabled: true
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
  labels:
    label-one: "value-one"
  name: {BUCKET_NAME_2}
  namespace: foo
spec:
  bucketPolicyOnly: true
  versioning:
    enabled: true