apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {INSTANCE_NAME_1}
  namespace: foo
spec:
  region: us-central1
  databaseVersion: MYSQL_5_7
  settings:
    tier: db-n1-standard-1
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  labels:
    label-one: "value-one"
  name: {DB_NAME_1}
  namespace: foo
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: {INSTANCE_NAME_1}
---
apiVersion: v1
kind: Secret
metadata:
  name: {DB_USER_PWD_1}
  namespace: foo
data:
  password: cGFzc3dvcmQ=
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {DB_USER_1}
  namespace: foo
spec:
  instanceRef:
    name: {DB_NAME_1}
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: {DB_USER_PWD_1}
        key: password
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {INSTANCE_NAME_2}
  namespace: foo
spec:
  region: us-central1
  databaseVersion: MYSQL_5_7
  settings:
    tier: db-n1-standard-1
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  labels:
    label-one: "value-one"
  name: {DB_NAME_2}
  namespace: foo
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: {INSTANCE_NAME_2}
---
apiVersion: v1
kind: Secret
metadata:
  name: {DB_USER_PWD_2}
  namespace: foo
data:
  password: cGFzc3dvcmQ=
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {DB_USER_2}
  namespace: foo
spec:
  instanceRef:
    name: {DB_NAME_2}
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: {DB_USER_PWD_2}
        key: password