apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app
  labels:
    app: foo-app
spec:
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      serviceAccountName: foo-runner
      containers:
      - name: foo
        image: gcr.io/cshou-playground/foo-252dace3948abf4ae24e75d0c09e136a@sha256:cb3e2811e1e51622c145cac4bdfaa5375f739eafc7372e742ed3f2b91ecf7042
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: foo-app
spec:
  selector:
    app: foo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080