apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: foo-app-ksvc
  labels:
    app: foo-app
spec:
  template:
    spec:
      serviceAccountName: foo-runner
      containers:
      - name: foo
        image: gcr.io/cshou-playground/foo-252dace3948abf4ae24e75d0c09e136a@sha256:cb3e2811e1e51622c145cac4bdfaa5375f739eafc7372e742ed3f2b91ecf7042
        ports:
        - containerPort: 8080

