# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.backing.google.com
  labels:
    backing.google.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: backing-webhook
      namespace: gcp-backing
  failurePolicy: Fail
  name: webhook.backing.google.com
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.backing.google.com
  labels:
    backing.google.com/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: backing-webhook
      namespace: gcp-backing
  failurePolicy: Fail
  name: validation.webhook.backing.google.com
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.backing.google.com
  labels:
    serving.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: backing-webhook
      namespace: gcp-backing
  failurePolicy: Fail
  name: config.webhook.backing.google.com
  namespaceSelector:
    matchExpressions:
    - key: backing.google.com/release
      operator: Exists
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: bindings.webhook.backing.google.com
  labels:
    eventing.knative.dev/release: devel
webhooks:
- admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: backing-webhook
      namespace: gcp-backing
  failurePolicy: Fail
  sideEffects: None
  name: bindings.webhook.backing.google.com
---
apiVersion: v1
kind: Secret
metadata:
  name: backing-webhook-certs
  namespace: gcp-backing
  labels:
    backing.google.com/release: devel
# The data is populated at install time.
